### ISSUE TITLE
Attachment Download Not working?

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#4] opened 2015-11-11 15:43 UTC
One IOS app user on my forum reported that he can't download .rar attachment.

**Comment by vbresults** [comment] 2015-11-12 00:18
What happens when they click the link?

**Comment by RoldanLT** [comment] 2015-11-12 02:10
Just nothing happens when they tap the attachment link.

**Comment by vbresults** [comment] 2015-11-12 02:11
How do we reach this on the app

**Comment by RoldanLT** [comment] 2015-11-12 02:20
Do you mean how to re-produce?
We have this thread/topic with .rar file attached, when an IOS user try to download the file just nothing happens.

Or do you mean something?

**Comment by vbresults** [comment] 2015-11-12 02:21
Yes, what thread

**Comment by RoldanLT** [comment] 2015-11-12 02:23
I'm asking the user now who reported.

**Comment by vbresults** [comment] 2015-11-12 11:14
This issue has been confirmed, duplicate of #6.

**Closed by vbresults** 2015-11-12 11:14 UTC
Labels: need more information
