### ISSUE TITLE
Several Server Errors

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#15] opened 2015-11-16 06:54 UTC
Some error log after update:

Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: Unknown Account, 17 minutes ago
Stack Trace
#0 /public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(25): MobileInterface_PushAlert_Transport::send('messages', Array)
#2 /public/library/MobileInterface/Listener.php(46): MobileInterface_PushAlert_Transport::messages(Array)
#3 [internal function]: MobileInterface_Listener::pushAlertQueueSend(Array)
#4 /public/library/XenForo/Model/Cron.php(357): call_user_func(Array, Array)
#5 /public/library/XenForo/Deferred/Cron.php(24): XenForo_Model_Cron->runEntry(Array)
#6 /public/library/XenForo/Model/Deferred.php(295): XenForo_Deferred_Cron->execute(Array, Array, 7.9999990463257, '')
#7 /public/library/XenForo/Model/Deferred.php(429): XenForo_Model_Deferred->runDeferred(Array, 7.9999990463257, '', false)
#8 /public/library/XenForo/Model/Deferred.php(374): XenForo_Model_Deferred->_runInternal(Array, NULL, '', false)
#9 /public/deferred.php(23): XenForo_Model_Deferred->run(false)
#10 {main}
Request State
array(3) {
["url"] => string(37) "/deferred.php"
["_GET"] => array(0) {
}
["_POST"] => array(3) {
["_xfRequestUri"] => string(53) "/f/smart-talk-n-text-sun.135/page-25?order=view_count"
["_xfNoRedirect"] => string(1) "1"
["_xfResponseType"] => string(4) "json"
}
}

Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: vinzoimartinez, 48 minutes ago
Stack Trace
#0 /public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#2 /public/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Milano_LiveFeed_ControllerPublic_Account))
#3 /public/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#4 /public/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /public/index.php(13): XenForo_FrontController->run()
#6 {main}
Request State
array(3) {
["url"] => string(61) "/index.php?account/push-alert-register"
["_GET"] => array(1) {
["account/push-alert-register"] => string(0) ""
}
["_POST"] => array(4) {
["_xfResponseType"] => string(4) "json"
["_xfToken"] => string(8) "********"
["platform"] => string(7) "android"
["token"] => string(152) "fxx-0NwConk:APA91bGQHUWmuSn8OJhrash0B1lHuI0aa_MSZV-_6JOn7gK5bjzY3p58bKOARrCl66M4wTu4DCd_KutqTsZWhcR7XK5KOAfM1WlArQyGr6yt5NPETcqcKtp72EJjb0noq6RyrwQDJrcM"
}
}

Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: Unknown Account, Today at 11:02 AM
Stack Trace
#0 /public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(25): MobileInterface_PushAlert_Transport::send('messages', Array)
#2 /public/library/MobileInterface/Listener.php(46): MobileInterface_PushAlert_Transport::messages(Array)
#3 [internal function]: MobileInterface_Listener::pushAlertQueueSend(Array)
#4 /public/library/XenForo/Model/Cron.php(357): call_user_func(Array, Array)
#5 /public/library/XenForo/Deferred/Cron.php(24): XenForo_Model_Cron->runEntry(Array)
#6 /public/library/XenForo/Model/Deferred.php(295): XenForo_Deferred_Cron->execute(Array, Array, 7.9999978542328, '')
#7 /public/library/XenForo/Model/Deferred.php(429): XenForo_Model_Deferred->runDeferred(Array, 7.9999978542328, '', false)
#8 /public/library/XenForo/Model/Deferred.php(374): XenForo_Model_Deferred->_runInternal(Array, NULL, '', false)
#9 /public/deferred.php(23): XenForo_Model_Deferred->run(false)
#10 {main}
Request State
array(3) {
["url"] => string(36) "/deferred.php"
["_GET"] => array(0) {
}
["_POST"] => array(3) {
["_xfRequestUri"] => string(1) "/"
["_xfNoRedirect"] => string(1) "1"
["_xfResponseType"] => string(4) "json"
}
}

Server Error Log
Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: cyverboy1993, Today at 1:06 PM
Stack Trace
#0 /home/nginx/domains/phcorner.net/public/library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /public/library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#2 /public/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Milano_LiveFeed_ControllerPublic_Account))
#3 /public/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#4 /public/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /public/index.php(13): XenForo_FrontController->run()
#6 {main}
Request State
array(3) {
["url"] => string(61) "/index.php?account/push-alert-register"
["_GET"] => array(1) {
["account/push-alert-register"] => string(0) ""
}
["_POST"] => array(4) {
["_xfResponseType"] => string(4) "json"
["_xfToken"] => string(8) "********"
["platform"] => string(7) "android"
["token"] => string(152) "fF2NgBuHq8M:APA91bFaE678e3QuFM92Irpsxn87hq543vsITwX3H4ugSBFgdwXTGbIFe6v6cn0xIdFxYfYHDvJq0BSTJa_DCxNhY2eHS4iyF5jSdxa_aSmuSEC_c06bTnfwjE9KCfjOJk8_8h39J6er"
}
}

**Comment by vbresults** [comment] 2015-11-16 07:15
This time the problem is isolated to your site, as I am receiving alerts elsewhere and not seeing these errors; do you see a message in the server error log for any messages you send out?

**Comment by RoldanLT** [comment] 2015-11-16 07:16
That's the only server error logs I received since I update to 1.1.32.

**Comment by vbresults** [comment] 2015-11-16 07:18
Do you have command line access to your server?

**Comment by RoldanLT** [comment] 2015-11-16 07:19
Yes of course I have. all the access.
Why?
I didn't encounter any errors now though.

**Comment by vbresults** [comment] 2015-11-16 07:21
Send the output of this --
```
curl http://apps.vbresults.com/push_notifications/register
```

I think the reason this is happening now is because after the fixes 100% of the alerts are coming thru and it might be too many concurrent requests for your server.

**Comment by RoldanLT** [comment] 2015-11-16 07:22
# curl http://apps.vbresults.com/push_notifications/register
{"conditions":{"query_notempty":false,"arg_api_key_notempty":false,"arg_platform_notempty":false,"arg_token_notempty":false,"arg_external_user_id_notempty":false,"auth_find_client_notempty":false,"auth_find_device_empty":false},"error":true}[root@server8 ~]#

**Comment by vbresults** [comment] 2015-11-16 07:25
Run this for 60 seconds and let me know if any of the requests fail:
```
watch curl http://apps.vbresults.com/push_notifications/register
```

**Comment by RoldanLT** [comment] 2015-11-16 07:37
Uploaded a full screen cast/video for you: https://www.dropbox.com/s/2rp7a2ci8raqg97/screencast-2015-11-16-153335.webm?dl=0

**Comment by RoldanLT** [comment] 2015-11-16 07:38
New server errors: Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: Unknown Account, 8 minutes ago
Stack Trace
#0 /library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /library/MobileInterface/PushAlert/Transport.php(25): MobileInterface_PushAlert_Transport::send('messages', Array)
#2 /library/MobileInterface/Listener.php(46): MobileInterface_PushAlert_Transport::messages(Array)
#3 [internal function]: MobileInterface_Listener::pushAlertQueueSend(Array)
#4 /library/XenForo/Model/Cron.php(357): call_user_func(Array, Array)
#5 /library/XenForo/Deferred/Cron.php(24): XenForo_Model_Cron->runEntry(Array)
#6 /library/XenForo/Model/Deferred.php(295): XenForo_Deferred_Cron->execute(Array, Array, 7.9999980926514, '')
#7 /library/XenForo/Model/Deferred.php(429): XenForo_Model_Deferred->runDeferred(Array, 7.9999980926514, '', false)
#8 /library/XenForo/Model/Deferred.php(374): XenForo_Model_Deferred->_runInternal(Array, NULL, '', false)
#9 /deferred.php(23): XenForo_Model_Deferred->run(false)
#10 {main}
Request State
array(3) {
  ["url"] => string(37) "/deferred.php"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(4) {
    ["_xfRequestUri"] => string(18) "/f/-/create-thread"
    ["_xfNoRedirect"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
}



Error Info
Zend_Http_Client_Exception: Unable to read response, or response is empty - library/Zend/Http/Client.php:993
Generated By: elzzur, 5 minutes ago
Stack Trace
#0 /library/MobileInterface/PushAlert/Transport.php(40): Zend_Http_Client->request('POST')
#1 /library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#2 /library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Milano_LiveFeed_ControllerPublic_Account))
#3 /library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#4 /library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#5 /index.php(13): XenForo_FrontController->run()
#6 {main}
Request State
array(3) {
  ["url"] => string(61) "/index.php?account/push-alert-register"
  ["_GET"] => array(1) {
    ["account/push-alert-register"] => string(0) ""
  }
  ["_POST"] => array(4) {
    ["_xfResponseType"] => string(4) "json"
    ["_xfToken"] => string(8) "********"
    ["platform"] => string(7) "android"
    ["token"] => string(152) "cdy-I-2gHj0:APA91bGAHQMAVvwckP47D4iR_kKJn5E8gIS8wIFTkJDadb_-h50HCv8U2ayvQKW957yRugCs4UJRzD-msbh90PCf1Lopz_SsB0OP5iigsYofGW-MSwoyCSDKBW9ZyQgsrvxHc8VInpuP"
  }
}

**Comment by vbresults** [comment] 2015-11-16 08:06
If you reboot the server does this fix it?

**Comment by RoldanLT** [comment] 2015-11-16 08:34
Wait, why needs rebooting?
I already did restart PHP-FPM and NGINX.

**Comment by vbresults** [comment] 2015-11-16 08:52
Just trying to isolate the problem.

**Comment by RoldanLT** [comment] 2015-11-16 08:54
I already restart PHP-NGINX again this time.

**Comment by vbresults** [comment] 2015-11-16 08:56
The whole server.

**Comment by RoldanLT** [comment] 2015-11-17 00:09
Let's observe, I just rebooted the whole server.

**Comment by vbresults** [comment] 2015-11-17 01:32
It doesn't look like the add-on is enabled

**Comment by RoldanLT** [comment] 2015-11-17 01:53
I have to disable it for now, as I am still receiving a lot of error.
Like this one reported: https://www.phcorner.net/t/help-mga-k-ph.107846/#post-849135

**Comment by vbresults** [comment] 2015-11-17 02:46
Did you confirm whether or not it's happening with clean cache?

**Comment by RoldanLT** [comment] 2015-11-17 03:21
They are new visitors so no cache for their browser.

**Comment by vbresults** [comment] 2015-11-17 03:50
What device and android version is producing this?

**Comment by RoldanLT** [comment] 2015-11-17 04:13
I ask him just now: https://www.phcorner.net/t/help-mga-k-ph.107846/#post-849846

**Comment by vbresults** [comment] 2015-11-18 08:37
Any updates on this?

**Comment by RoldanLT** [comment] 2015-11-18 09:02
Samsung S2, Android Jellybean.

**Comment by vbresults** [comment] 2015-11-18 09:04
Not the device, I mean the errors -- did the restart help.  And the alerts/popups have been fixed in the most recent XenForo add-on version.

**Comment by RoldanLT** [comment] 2015-11-18 09:09
Fixed on Mobile Interface #vbresults 1.1.33 ?
I will enable back the addon and will observe again for the server error.

**Comment by vbresults** [comment] 2015-11-18 09:14
Yes.

**Comment by vbresults** [comment] 2015-11-19 01:51
Have the errors stopped?

**Comment by RoldanLT** [comment] 2015-11-19 02:04
Yes no more errors now.

**Closed** 2015-11-19 02:06 UTC
Labels: invalid
