### ISSUE TITLE
iOS app links not working.

### ISSUE THREAD

**Issue by baustin75** [vbresults/mobile-apps-for-xenforo#20] opened 2015-12-02 23:04 UTC
In iOS the Xenforo links are not clickable.  They might be clickable once or twice then they stop working all together.  You can see the Xenforo progress bar working and then disappear.  I have tried the Stable, Latest and Alpha versions with the same issue.  I have incremented the Cache Reset and I am using the latest version 1.1.36.   The Android version is working with no issues.

**Comment by vbresults** [comment] 2015-12-03 04:08
We can reproduce this on some devices; what iOS devices can you produce this on?

**Comment by vbresults** [comment] 2015-12-04 02:52
May have found the cause of this, increment the counter and let me know if it's fixed for you.

**Comment by baustin75** [comment] 2015-12-04 04:27
I just tried it on the iPad and it maybe seems a little better.  Once you
force kill the app and go back in it's always good for 1 or 2 clicks and
then just dies.  Wierd.  I tried all the versions and I incremented the
counter each time too.   Thanks.

**Comment by vbresults** [comment] 2015-12-04 09:58
If you wait 10 seconds before clicking anything, do the links work?

**Comment by bloh2** [comment] 2015-12-04 16:25
Tested. The link will only work if I waited long enough before clicking the link.

**Comment by vbresults** [comment] 2015-12-05 01:29
I just tested the fix and confirmed it works on BAF.  You'll have to wait for the admin to increment the counter so it force clears the app cache, you can also force kill the app and it may clear the cache too.

**Comment by bloh2** [comment] 2015-12-05 10:26
I downloaded BAF. It can click link without waiting for 10+ seconds. But then, after continuously clicking a few links, it stopped working again.

**Comment by vbresults** [comment] 2015-12-05 10:30
The page needs 1 or 2 seconds to load before you click a link; it's not ideal but until our upstream provider fixes the underlying issue, this is the best fix we have.  Can you confirm?

**Comment by baustin75** [comment] 2015-12-05 14:20
I can also report the same behavior.  "I downloaded BAF. It can click link
without waiting for 10+ seconds. But then, after continuously clicking a
few links, it stopped working again."

Although it better than before.  Clicking too fast seems to break the app.

**Comment by vbresults** [comment] 2015-12-05 15:11
@baustin75 is it still 10 seconds for you or has the time shortened?  Just had an idea that will remove the last 2 seconds without the upstream provider's help, but it will require an app update; please confirm if it's 10+ seconds now or closer to 1-2 seconds.

**Comment by baustin75** [comment] 2015-12-05 15:21
I just tested it.  It appears to be closer to 2 seconds.  Thanks.

**Comment by vbresults** [comment] 2015-12-05 15:47
Great!  We'll have the add-on based fix out on Tuesday.

**Comment by baustin75** [comment] 2015-12-05 16:44
I really appreciate your help with all of this.  Thanks!!!

**Comment by bloh2** [comment] 2015-12-16 10:33
The link didn't work again. I tried BAF.
And sometimes it just stuck on the homepage.

**Comment by bloh2** [comment] 2015-12-16 10:41
Sometimes, when it navigates to other pages, it will just stuck on the white screen, even though there is internet connection.

**Comment by vbresults** [comment] 2015-12-17 08:03
This is fixed in the 1.1.39 app update; it has to be approved by apple and then installed to take effect.

**Comment by vbresults** [comment] 2015-12-18 08:52
@bloh2 the white screen issue is separate and belongs in another ticket; that said, at this point addressing them is eating into the time for existing clients and we cannot accept any more unless you are also also a client.  Thank you for your submissions and regards.

**Closed by vbresults** 2015-12-18 08:52 UTC
Labels: bug
