### ISSUE TITLE
2 Pop up errors

### ISSUE THREAD

**Issue by RoldanLT** [vbresults/mobile-apps-for-xenforo#11] opened 2015-11-15 02:08 UTC
I encounter this yesterday, with previous app/addon version. I after this 2 pop ups, browser hangs up and not usable.

http://i.imgur.com/AnOWLnX.png
http://i.imgur.com/qIlDzoJ.png

**Comment by vbresults** [comment] 2015-11-15 02:16
Fixed in the latest version

**Comment by RoldanLT** [comment] 2015-11-15 02:23
I have to disable the addon for now because of this new pop up error.

http://i.imgur.com/4gpIuad.png

**Comment by RoldanLT** [comment] 2015-11-15 02:24
That error just happen to me last few minutes.
You must have changed something on the back-end? 
Thanks for the quick response.

**Comment by vbresults** [comment] 2015-11-15 02:25
If you clear app data is it fixed?

**Comment by RoldanLT** [comment] 2015-11-15 02:31
Force stop, clear data > no pop up error.
I think that error only appear when you have unread alerts.

**Comment by RoldanLT** [comment] 2015-11-15 02:35
Not happening again for me, even with unread/new alerts.
You did some changes right? :)
Thanks!
Still no push notifications for me Android 4.1.2 :(.

**Comment by vbresults** [comment] 2015-11-15 02:45
Send a PM to testuser123

**Comment by RoldanLT** [comment] 2015-11-15 02:46
Done (y).

**Comment by RoldanLT** [comment] 2015-11-15 02:54
The 2 errors happen again on Mobile browsers :(.

**Comment by vbresults** [comment] 2015-11-15 02:55
Is their cache cleared?

**Comment by RoldanLT** [comment] 2015-11-15 02:56
Yes I cleared last 25 mins: https://github.com/vbresults/mobile-apps-for-xenforo/issues/11#issuecomment-156771466

**Comment by vbresults** [comment] 2015-11-15 02:57
What browser?

**Comment by RoldanLT** [comment] 2015-11-15 03:00
Default Samsung Browser.

(I disabled the addon for now as guest can't visit my site for that error).

**Comment by vbresults** [comment] 2015-11-15 03:02
Please turn it back on for 15 minutes so we can fix and confirm

**Comment by RoldanLT** [comment] 2015-11-15 03:06
Turn on now.
By the way, I have Guest view Nginx fastcgi Full Page caching for 10 minutes.
So guest will update next 10 minutes also.

**Comment by RoldanLT** [comment] 2015-11-15 03:09
To bypass Guest Full page cache, please visit a random thread. Very OLD thread mostly not cached.
Like: http://www.phcorner.net/t/555/

**Comment by vbresults** [comment] 2015-11-15 03:12
Found an fixed the popup problem

**Comment by RoldanLT** [comment] 2015-11-15 03:13
How to apply the fix Sir?
Thanks!

**Comment by vbresults** [comment] 2015-11-15 03:13
Nothing for you to do, this is fixed on our CDN and your page cache doesn't cause a problem since it's our CDN

**Comment by vbresults** [comment] 2015-11-15 03:15
Confirmed fixed looks like we don't have to clear browser cache, and it revealed a bug in the custom style detection too but that's not as urgent as the push issue reported, looking into that now

**Comment by vbresults** [comment] 2015-11-15 03:16
Ah wait, it's not taking effect, looks like I do have to clear cache

**Comment by vbresults** [comment] 2015-11-15 03:22
Please open a separate issue for the alerts

**Closed by vbresults** 2015-11-15 03:22 UTC
Labels: bug

**Comment by RoldanLT** [comment] 2015-11-15 03:25
And it's fixed already now?
Cause I still seeing it on every pages I visit on the site.
I can even replicate it as login member and just use Desktop Browser with Android user agent :|.

**Comment by RoldanLT** [comment] 2015-11-15 03:28
http://i.imgur.com/MlYlxSW.png
http://i.imgur.com/utY4P8D.png

**Comment by RoldanLT** [comment] 2015-11-15 03:34
And not receiving pop error now.

**Comment by RoldanLT** [comment] 2015-11-15 04:02
After this commnet: https://github.com/vbresults/mobile-apps-for-xenforo/issues/11#issuecomment-156775357
What changes have been made?
Seems fine now.

**Comment by RoldanLT** [comment] 2015-11-15 04:54
By the way, I'm still receiving this on Default browser of Samsung :(.

**Comment by vbresults** [comment] 2015-11-15 08:05
This shouldn't be in the code anymore, is it from the cache, or already cleared?

**Comment by RoldanLT** [comment] 2015-11-15 08:54
I already cleared all my phone Default Browser Data, Cache, Cookies.

**Comment by vbresults** [comment] 2015-11-15 14:37
Sent you a message on the forum again

**Comment by RoldanLT** [comment] 2015-11-17 01:54
Now 5 error pop ups: https://www.phcorner.net/t/help-mga-k-ph.107846/#post-849135
I have to disable the addon.
