### ISSUE TITLE
iOS login persistence and and push notifications 

### ISSUE THREAD

**Issue by Dannymh** [vbresults/mobile-apps-for-xenforo#54] opened 2016-03-09 08:30 UTC
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
Since upgrading the addon to the latest version the login does not persist on iOS device. Push notifications are not making it through to the iOS device.
If I close the app I have to login again

I have tried removing the app and re-installing it.

The same happens on my iPhone 6s and my iPad both on latest iOS 

### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App:  1.1.40
- Android App:

- Platform: XenForo/vBulletin/WordPress
- Add-on Version:
- XenForo Version: 1.5.6

### 1.4. Please tell us how to recreate the issue in detail
Install app, login and accept notifications.

Post >> close app >> open app >> you will be asked to login again and no notifications have been sent

### 1.5. Is there an error message involved?  If so, please paste
Am getting ocassional errors such as

Zend_Http_Client_Adapter_Exception: Read timed out after 10 seconds - library/Zend/Http/Client/Adapter/Socket.php:512

`#0 /var/www/htdocs/st/library/Zend/Http/Client/Adapter/Socket.php(330): Zend_Http_Client_Adapter_Socket->_checkSocketReadTimeout()
#1 /var/www/htdocs/st/library/Zend/Http/Client.php(989): Zend_Http_Client_Adapter_Socket->read()
#2 /var/www/htdocs/st/library/MobileInterface/PushAlert/Transport.php(42): Zend_Http_Client->request('POST')
#3 /var/www/htdocs/st/library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#4 /var/www/htdocs/st/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Valhalla_LikesGiven_ControllerPublic_Account))
#5 /var/www/htdocs/st/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#6 /var/www/htdocs/st/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#7 /var/www/htdocs/st/index.php(13): XenForo_FrontController->run()
#8 {main}`

`array(3) {
  ["url"] => string(64) "http://www.silvertails.net/index.php?account/push-alert-register"
  ["_GET"] => array(1) {
    ["account/push-alert-register"] => string(0) ""
  }
  ["_POST"] => array(4) {
    ["_xfResponseType"] => string(4) "json"
    ["_xfToken"] => string(8) "********"
    ["platform"] => string(3) "ios"
    ["token"] => string(64) "347ca84fc15d96f08101fdb0fb10a9a456d2907eaf69e75235385fd35ee8d672"
  }
}`

this may be related as it is registering the alerts, but my user is not triggering this same server error, these are maybe once per day where as alerts are not going out at all for iOS

**Comment by Dannymh** [comment] 2016-03-09 09:28
Am getting ocassional errors such as

Zend_Http_Client_Adapter_Exception: Read timed out after 10 seconds - library/Zend/Http/Client/Adapter/Socket.php:512

`#0 /var/www/htdocs/st/library/Zend/Http/Client/Adapter/Socket.php(330): Zend_Http_Client_Adapter_Socket->_checkSocketReadTimeout()
#1 /var/www/htdocs/st/library/Zend/Http/Client.php(989): Zend_Http_Client_Adapter_Socket->read()
#2 /var/www/htdocs/st/library/MobileInterface/PushAlert/Transport.php(42): Zend_Http_Client->request('POST')
#3 /var/www/htdocs/st/library/MobileInterface/PushAlert/Transport.php(14): MobileInterface_PushAlert_Transport::send('register', Array)
#4 /var/www/htdocs/st/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(Valhalla_LikesGiven_ControllerPublic_Account))
#5 /var/www/htdocs/st/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#6 /var/www/htdocs/st/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#7 /var/www/htdocs/st/index.php(13): XenForo_FrontController->run()
#8 {main}`

`array(3) {
  ["url"] => string(64) "http://www.silvertails.net/index.php?account/push-alert-register"
  ["_GET"] => array(1) {
    ["account/push-alert-register"] => string(0) ""
  }
  ["_POST"] => array(4) {
    ["_xfResponseType"] => string(4) "json"
    ["_xfToken"] => string(8) "********"
    ["platform"] => string(3) "ios"
    ["token"] => string(64) "347ca84fc15d96f08101fdb0fb10a9a456d2907eaf69e75235385fd35ee8d672"
  }
}`

this may be related as it is registering the alerts, but my user is not triggering this same server error, these are maybe once per day where as alerts are not going out at all for iOS

**Comment by Dannymh** [comment] 2016-03-10 09:54
The login persistence issue was caused by having the app on two devices. Once I removed it from my iPad login persisted on my iPhone.

Alerts/push notifications are still not working

**Comment by vbresults** [comment] 2016-03-11 01:23
If you install 1.1.41 of the iOS app, is the issue resolved?

**Comment by Dannymh** [comment] 2016-03-11 07:12
Same issue with the 1.1.41 iOS app.
Login persistence seems better but occasionally drops.

Alerts are not coming through to any iOS user android users say the are still getting push alerts

**Comment by vbresults** [comment] 2016-03-11 07:22
Do you see a "Notifications" item under Settings > Your App Name

**Comment by Dannymh** [comment] 2016-03-11 07:28
Yes, all are also switched on

http://postimg.org/image/pc3stlk0n/
http://postimg.org/image/5uvlxffzl/

I tried updating he js cache on the forum plugin settings and also uninstalled the app removed all internet and app cache on my phone rebooted and reinstalled

**Comment by vbresults** [comment] 2016-03-11 07:33
Email updates+pma@vbresults.com with your Intermediary Push Server Key

**Comment by vbresults** [comment] 2016-03-11 07:42
What is your numeric user id on the forum?  Don't need the username

**Comment by Dannymh** [comment] 2016-03-11 07:54
User id is 2

**Comment by vbresults** [comment] 2016-03-11 08:07
Just tried to send you a direct alert; did you receive it?

**Comment by Dannymh** [comment] 2016-03-11 08:09
No nothing came through. On my phone

**Comment by vbresults** [comment] 2016-03-11 08:12
Uninstall the app one more time and reinstall, this is to see if we get your push token registered on our end

**Comment by Dannymh** [comment] 2016-03-11 08:20
Hi,

Ok uninstalled, hard rebooted my phone, installed app again and logged in

Dan

**Comment by vbresults** [comment] 2016-03-11 08:24
The device did not register; please create a regular test user account and provide the login details via email, and I'll find out what's happening using my iPhone

**Comment by Dannymh** [comment] 2016-03-11 08:31
Hi,

You can use the following user

Username: dantestinguser
Password: 7hi5i5ap@ss

Kind Regards
Dan Hewes

**Comment by vbresults** [comment] 2016-03-11 09:25
This user isn't confirmed

**Comment by Dannymh** [comment] 2016-03-11 09:27
Hi,

Sorry that should be fixed now

Dan

On Fri, Mar 11, 2016 at 10:25 AM, vB Results, LLC. <notifications@github.com

**Comment by vbresults** [comment] 2016-03-11 09:48
Dan,

Thank you for the quick responses and help in diagnosing the problem, it has been fixed -- this was an issue on the push server that prevented any devices from registering in the past 6 days.

This affected approximately 77 devices and did not affect any of the devices that registered before 6 days ago, which is why this was tricky to pin down.  Anyway, it's fixed on our end now;

If anyone mentions not receiving alerts, tell them to log out and log back in, and that will resolve the issue.  @reddyinc this is likely what was causing your problems.

**Comment by Dannymh** [comment] 2016-03-11 09:49
Excellent thank you for the support!

**Comment by vbresults** [comment] 2016-03-11 09:59
@Dannymh Sure thing, and in regards to the logout issue, we do not touch the login system with our add-on in any way since we do not use an API.

If you can find something about this issue that is unique to our apps, please open a new ticket as we'll have a starting point to track down the issue.

p.s. If you haven't yet left a review, you can do so here: https://xenforo.com/community/resources/mobile-apps-for-xenforo-with-push-notifications-and-add-on-support-android-iphone-ipad.4731/reviews

**Closed** 2016-03-11 10:00 UTC
Labels: bug, fixed, push server

**Comment by Dannymh** [comment] 2016-03-11 10:01
I wanted to leave a review the other day, but because I purchased this directly through the native app one, I am not on the list of users for owning the PMA app so I cant leave a review and dont get updates through xenforo.

I am not sure if there is anyway to fix that

**Comment by vbresults** [comment] 2016-03-11 10:06
The XenForo.com resource simply links to our PayPal checkout, there is no sharing of our client database with XenForo.com's resource manager that allows/prevents you from reviewing, it's open to all

**Comment by Dannymh** [comment] 2016-03-11 10:19
oh wow ok, freview provided

**Comment by vbresults** [comment] 2016-03-11 10:27
Thank you (:

**Comment by Dannymh** [comment] 2016-03-11 10:29
I will have to log another ticket. Alerts are coming through. But the alerts in iOS are only opening the app to the root page again and not the post in the alert

**Comment by vbresults** [comment] 2016-03-11 10:36
Re-opened #39
