### ISSUE TITLE
Network error: IOS link click too fast

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps-for-xenforo#48] opened 2016-03-04 12:35 UTC
When IOS link click too fast, it shows network error. I did mention it before in xenforo conversation.

![image](https://cloud.githubusercontent.com/assets/11502455/13527226/8ad04ab6-e248-11e5-8ba3-06e596622539.png)

**Comment by vbresults** [comment] 2016-03-04 13:11
Duplicate of #33 .

**Closed by vbresults** 2016-03-04 13:11 UTC
